name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Racket environment
      uses: Bogdanp/setup-racket@v0.8

    - name: Cache dependencies
      uses: actions/cache@v2.0.0
      with:
        path: ~/.racket
        key: ${{ runner.os }}-raco-${{ hashFiles('dependencies/raco-requirements.txt') }}

    - name: Install dependencies
      run: |
        cd dependencies
        sh install-deps.sh
        cd ..
    
    - name: Run build script
      run: sh build.sh
      
    - name: Add and push
      run: |
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config user.name "Automation"
        git add -v docs/*
        git diff --staged --quiet && echo "No changes." || git commit -a -v -m "Build Pages" && git push -v
    
    - name: Trigger GitHub pages rebuild
      run: |
        curl --fail --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
        --header "Authorization: Bearer $USER_TOKEN"
      env:
        USER_TOKEN: ${{ secrets.USER_TOKEN }}

